[package]
name = "aredl-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5"
actix-rt = "2.9"
actix-cors = "0.7"
chrono = {version = "0.4", features = ["serde"]}
uuid = { version = "1.8", features = ["serde"] }
diesel = { version = "2.1", features = ["postgres", "r2d2", "chrono", "uuid"]}
diesel_migrations = "2.1"
openidconnect = { version = "3.5", features = ["reqwest"]}
futures-util = "0.3"
dotenv = "0.15"
env_logger = "0.11"
listenfd = "1.0"
lazy_static = "1.4"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
r2d2 = "0.8"
jsonwebtoken = { version = "9.3", features = ["default"] }
strum = {version = "0.26", features = ["strum_macros"]}
strum_macros = "0.26"
