# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.public]
file = "src/schema/public_schema.rs"
schema = "public"
custom_type_derives = ["diesel::query_builder::QueryId"]

[print_schema.aredl]
file = "src/schema/aredl_schema/generated.rs"
schema = "aredl"
custom_type_derives = ["diesel::query_builder::QueryId"]

[print_schema.arepl]
file = "src/schema/arepl_schema/generated.rs"
schema = "arepl"
custom_type_derives = ["diesel::query_builder::QueryId"]

[migrations_directory]
dir = "migrations"
