services:
  db:
    container_name: postgres-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aredl
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    container_name: api
    build: .
    restart: always
    ports:
      - "${API_HOST}:${API_PORT}:${API_PORT}"
    environment:
      HOST: "0.0.0.0"
      PORT: ${API_PORT}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}

      LEADERBOARD_REFRESH_SCHEDULE: ${LEADERBOARD_REFRESH_SCHEDULE}
      LEVEL_DATA_REFRESH_SCHEDULE: ${LEVEL_DATA_REFRESH_SCHEDULE}
      NOTIFICATIONS_CLEAN_SCHEDULE: ${NOTIFICATIONS_CLEAN_SCHEDULE}

      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      EDEL_SHEET_ID: ${EDEL_SHEET_ID}
      NLW_SHEET_ID: ${NLW_SHEET_ID}
    depends_on:
      - db
  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: tools/seed_aredl/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AREDL_DATA_GIT: ${AREDL_DATA_GIT}
      AREDL_DATA_PARENT: "/migrate_data/aredl_data"
    volumes:
      - migrate_data:/migrate_data
    depends_on:
      - db
    restart: "no"
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        sed "s|__API_PORT__|${API_PORT}|g" /etc/prometheus/prometheus.yml.template > /etc/prometheus/prometheus.yml && \
        /bin/prometheus \
          --config.file=/etc/prometheus/prometheus.yml \
          --storage.tsdb.path=/prometheus \
          --web.console.libraries=/usr/share/prometheus/console_libraries \
          --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - type: bind
        source: ./prometheus.yml.template
        target: /etc/prometheus/prometheus.yml.template
        read_only: true
      - prometheus_data:/prometheus
    ports:
      - "9080:9090"
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--docker_only=true'
      - '--disable_metrics=disk,diskIO,network,tcp,udp,percpu,sched,process'

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_URI: db:5432/aredl?sslmode=disable
      DATA_SOURCE_USER: ${POSTGRES_USER}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD} 
    command:
      - '--web.listen-address=:9187'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
volumes:
  db_data:
  test_db_data:
  migrate_data:
  prometheus_data: