services:
  db:
    container_name: postgres-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aredl
    ports:
      - "${API_DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: .
      args:
        BUILD_PROFILE: ${BUILD_PROFILE:-debug}
    restart: always
    ports:
      - "${API_HOST}:${API_PORT}:${API_PORT}"
    environment:
      HOST: "0.0.0.0"
      PORT: ${API_PORT}
      DOCS_API_SERVER: ${DOCS_API_SERVER}
      
      PEMONLIST_API_URL: https://pemonlist.com/api/player

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}

      MATVIEWS_REFRESH_SCHEDULE: ${MATVIEWS_REFRESH_SCHEDULE}
      LEVEL_DATA_REFRESH_SCHEDULE: ${LEVEL_DATA_REFRESH_SCHEDULE}
      DISCORD_AVATARS_REFRESH_SCHEDULE: ${DISCORD_AVATARS_REFRESH_SCHEDULE}
      DATA_CLEANER_SCHEDULE: ${DATA_CLEANER_SCHEDULE}
      RECURRING_SHIFTS_SCHEDULE: ${RECURRING_SHIFTS_SCHEDULE}

      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      EDEL_SHEET_ID: ${EDEL_SHEET_ID}
      NLW_SHEET_ID: ${NLW_SHEET_ID}

      GOOGLE_OAUTH_CLIENT: ${GOOGLE_OAUTH_CLIENT}
      GOOGLE_OAUTH_REFRESH: ${GOOGLE_OAUTH_REFRESH}
    depends_on:
      - db

volumes:
  db_data:
  test_db_data: