services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aredl
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - "${API_HOST}:${API_PORT}:${API_PORT}"
    environment:
      HOST: "0.0.0.0"
      PORT: ${API_PORT}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}

      LEADERBOARD_REFRESH_SCHEDULE: ${LEADERBOARD_REFRESH_SCHEDULE}
      LEVEL_DATA_REFRESH_SCHEDULE: ${LEVEL_DATA_REFRESH_SCHEDULE}
      NOTIFICATIONS_CLEAN_SCHEDULE: ${NOTIFICATIONS_CLEAN_SCHEDULE}

      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      EDEL_SHEET_ID: ${EDEL_SHEET_ID}
      NLW_SHEET_ID: ${NLW_SHEET_ID}
    depends_on:
      - db
  migrate:
    build:
      context: .
      dockerfile: tools/seed_aredl/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AREDL_DATA_GIT: ${AREDL_DATA_GIT}
      AREDL_DATA_PARENT: "/migrate_data/aredl_data"
    volumes:
      - migrate_data:/migrate_data
    depends_on:
      - db
    restart: "no"

volumes:
  db_data:
  test_db_data:
  migrate_data: