name: Backend CI/CD

on:
  workflow_dispatch:
  push:

env:
  CARGO_TERM_COLOR: always
  TEST_DATABASE_URL: postgres://postgres:password@localhost:5432/aredl_test
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
  DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
  DISCORD_REDIRECT_URI: ${{ secrets.DISCORD_REDIRECT_URI }}
  BUILD_PROFILE: release

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: aredl_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Installing rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: llvm-tools-preview

    - name: Cache cargo for main
      uses: Swatinem/rust-cache@v2

    - name: Run unit tests
      uses: actions-rs/cargo@v1
      with:
        command: test

  generate-code-coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: aredl_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      
      - name: Installing rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview

      - name: Cache cargo for main
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-tarpaulin
        run: |
          cargo install cargo-tarpaulin --version 0.32.7

      - name: Generate coverage report
        run: |
            cargo tarpaulin \
            --workspace \
            --out Lcov \
            --timeout 120 \
            --ignore-tests \
            --rustflags="-C opt-level=0" \
            --exclude-files "src/schema/*" "src/scheduled/*" "src/main.rs" "src/docs.rs" "src/utils/probe/*"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: false
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}

  build-api:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        - uses: actions/checkout@v4
        
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Set owner name to lowercase for docker compatibility
          run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          env:
            OWNER: '${{ github.repository_owner }}'
          
        - name: Build and push API image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            build-args: |
              BUILD_PROFILE=${{ env.BUILD_PROFILE }}
            tags: |
              ghcr.io/${{ env.OWNER_LC }}/aredl_backend_api:latest
              ghcr.io/${{ env.OWNER_LC  }}/aredl_backend_api:${{ github.sha }}
            cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LC  }}/aredl_backend_api:buildcache
            cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LC  }}/aredl_backend_api:buildcache,mode=max
  
  pre_deploy_backup:
    if: github.ref == 'refs/heads/main'
    needs: build-api
    uses: ./.github/workflows/db-backup.yml
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      GDRIVE_RCLONE_CONFIG: ${{ secrets.GDRIVE_RCLONE_CONFIG }}
  
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build-api, pre_deploy_backup]
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack_name: aredl_backend_stack
      remote_path: ~/
      docs_api_server: https://api.aredl.net/v2
      api_net: api_net
      db_alias: db_prod
      discord_redirect_uri: discord_redirect_uri_prod
    secrets:
      API_HOST: ${{ secrets.API_HOST }}
      API_PORT: ${{ secrets.API_PORT }}
      API_DB_PORT: ${{ secrets.API_DB_PORT }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_KEY:  ${{ secrets.DEPLOY_KEY }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

  build-api-dev:
    if: github.ref == 'refs/heads/dev'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
        - uses: actions/checkout@v4
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Set owner name to lowercase for docker compatibility
          run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          env:
            OWNER: '${{ github.repository_owner }}'
        - name: Build and push API dev image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            push: true
            build-args: |
              BUILD_PROFILE=${{ env.BUILD_PROFILE }}
            tags: |
              ghcr.io/${{ env.OWNER_LC }}/aredl_backend_api:dev
              ghcr.io/${{ env.OWNER_LC }}/aredl_backend_api:${{ github.sha }}
            cache-from: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/aredl_backend_api:buildcache
            cache-to: type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/aredl_backend_api:buildcache,mode=max

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build-api-dev
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack_name: aredl_backend_dev_stack
      remote_path: ~/dev
      docs_api_server: https://api.aredl.net/v2dev
      api_net: api_net_dev
      db_alias: db_dev
      discord_redirect_uri: discord_redirect_uri_dev
    secrets:
      API_HOST: ${{ secrets.DEV_API_HOST }}
      API_PORT: ${{ secrets.DEV_API_PORT }}
      API_DB_PORT: ${{ secrets.DEV_API_DB_PORT }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_KEY:  ${{ secrets.DEPLOY_KEY }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

  migrate-dev-db:
    if: github.ref == 'refs/heads/dev'
    needs: deploy-dev
    uses: ./.github/workflows/migrate-dev-db.yml
    secrets:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_KEY:  ${{ secrets.DEPLOY_KEY }}